wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-07
seed:
  desc: null
  value: 42
batch_size:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718637535
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
