site_name: ClimaX
repo_name: microsoft/ClimaX
repo_url: https://github.com/microsoft/ClimaX
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Lato
  palette:
    scheme: climax
  
extra_css:
  - stylesheets/extra.css
    
nav:
  - Home: "index.md"