wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-07
seed:
  desc: null
  value: 42
batch_size:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718637575
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      3:
      - 1
      - 3
      - 7
      - 16
      - 23
      - 63
      4: 3.8.16
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: train_loss_epoch
      6:
      - 3
      7:
      - 1
    - 1: val_loss
      6:
      - 3
      7:
      - 1
    - 1: test_loss
      6:
      - 3
      7:
      - 1
    - 1: train_f1_epoch
      6:
      - 3
      7:
      - 2
    - 1: val_f1
      6:
      - 3
      7:
      - 2
    - 1: test_f1
      6:
      - 3
      7:
      - 2
    - 1: train_precision_epoch
      6:
      - 3
      7:
      - 2
    - 1: val_precision
      6:
      - 3
      7:
      - 2
    - 1: test_precision
      6:
      - 3
      7:
      - 2
    - 1: train_avg_precision_epoch
      6:
      - 3
      7:
      - 2
    - 1: val_avg_precision
      6:
      - 3
      7:
      - 2
    - 1: test_avg_precision
      6:
      - 3
      7:
      - 2
    - 1: train_recall_epoch
      6:
      - 3
      7:
      - 2
    - 1: val_recall
      6:
      - 3
      7:
      - 2
    - 1: test_recall
      6:
      - 3
      7:
      - 2
    - 1: train_iou_epoch
      6:
      - 3
      7:
      - 2
    - 1: val_iou
      6:
      - 3
      7:
      - 2
    - 1: test_iou
      6:
      - 3
      7:
      - 2
